"""
Memory Manager Test
============================================================

Tests:

1. Database initialization
2. Save campaign
3. Retrieve campaign
4. Save user context
5. Retrieve user context
6. Search campaigns
7. Persistence after creating a new MemoryManager
8. Memory summary
"""

from app.memory.memory_manager import MemoryManager


# ============================================================
# TEST
# ============================================================

def main():

    print()
    print("=" * 60)
    print("MEMORY TEST - AI MARKETING STRATEGY MANAGER")
    print("=" * 60)

    # --------------------------------------------------------
    # Create memory manager
    # --------------------------------------------------------

    memory = MemoryManager()

    print()
    print("Database:")
    print(memory.database_path)

    # --------------------------------------------------------
    # TEST 1 - INITIALIZATION
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("TEST 1 - DATABASE INITIALIZATION")
    print("=" * 60)

    summary = memory.get_memory_summary()

    print()
    print("Memory summary:")
    print(summary)

    if memory.database_path.exists():
        print()
        print("DATABASE INITIALIZATION: PASS")
    else:
        print()
        print("DATABASE INITIALIZATION: FAIL")
        raise SystemExit(1)

    # --------------------------------------------------------
    # TEST 2 - SAVE CAMPAIGN
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("TEST 2 - SAVE CAMPAIGN")
    print("=" * 60)

    campaign_id = memory.save_campaign(
        campaign_name="AI Study Assistant Launch",
        product="AI-powered Study Assistant",
        target_audience="College students aged 18-25",
        marketing_goal="1,000 signups",
        budget="₹50,000",
        timeline="Not specified",
        strategy=(
            "Use social media, influencer marketing, "
            "content marketing and referral campaigns."
        ),
        final_output=(
            "Marketing strategy generated by the "
            "AI Marketing Strategy Manager."
        ),
        metadata={
            "source": "memory_test",
            "test_campaign": True,
        },
    )

    print()
    print("Saved campaign ID:")
    print(campaign_id)

    if campaign_id:
        print()
        print("SAVE CAMPAIGN: PASS")
    else:
        print()
        print("SAVE CAMPAIGN: FAIL")
        raise SystemExit(1)

    # --------------------------------------------------------
    # TEST 3 - RETRIEVE CAMPAIGN
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("TEST 3 - RETRIEVE CAMPAIGN")
    print("=" * 60)

    campaign = memory.get_campaign(
        campaign_id
    )

    print()
    print("Retrieved campaign:")
    print(campaign)

    if (
        campaign
        and campaign["product"]
        == "AI-powered Study Assistant"
        and campaign["budget"]
        == "₹50,000"
    ):
        print()
        print("RETRIEVE CAMPAIGN: PASS")
    else:
        print()
        print("RETRIEVE CAMPAIGN: FAIL")
        raise SystemExit(1)

    # --------------------------------------------------------
    # TEST 4 - SAVE USER CONTEXT
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("TEST 4 - SAVE USER CONTEXT")
    print("=" * 60)

    memory.save_context(
        "preferred_product",
        "AI-powered Study Assistant",
    )

    memory.save_context(
        "preferred_audience",
        "College students aged 18-25",
    )

    memory.save_context(
        "default_budget",
        "₹50,000",
    )

    memory.save_context(
        "marketing_preferences",
        {
            "channels": [
                "Instagram",
                "Influencers",
                "Content Marketing",
            ],
            "goal_type": "Signups",
        },
    )

    print()
    print("Saved user context.")

    context = memory.get_all_context()

    print()
    print("Current context:")
    print(context)

    if (
        context.get("preferred_product")
        == "AI-powered Study Assistant"
    ):
        print()
        print("SAVE USER CONTEXT: PASS")
    else:
        print()
        print("SAVE USER CONTEXT: FAIL")
        raise SystemExit(1)

    # --------------------------------------------------------
    # TEST 5 - SEARCH CAMPAIGNS
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("TEST 5 - SEARCH CAMPAIGNS")
    print("=" * 60)

    results = memory.search_campaigns(
        "Study Assistant"
    )

    print()
    print("Search results:")
    print(results)

    if len(results) > 0:
        print()
        print("SEARCH CAMPAIGNS: PASS")
    else:
        print()
        print("SEARCH CAMPAIGNS: FAIL")
        raise SystemExit(1)

    # --------------------------------------------------------
    # TEST 6 - PERSISTENCE
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("TEST 6 - PERSISTENT MEMORY")
    print("=" * 60)

    print()
    print(
        "Creating a NEW MemoryManager instance..."
    )

    # Important:
    # This simulates a new application/session.
    new_memory = MemoryManager()

    persisted_campaign = (
        new_memory.get_campaign(
            campaign_id
        )
    )

    persisted_context = (
        new_memory.get_context(
            "preferred_product"
        )
    )

    print()
    print("Campaign retrieved from new instance:")
    print(persisted_campaign)

    print()
    print("Context retrieved from new instance:")
    print(persisted_context)

    if (
        persisted_campaign is not None
        and persisted_context
        == "AI-powered Study Assistant"
    ):
        print()
        print("PERSISTENT MEMORY: PASS")
    else:
        print()
        print("PERSISTENT MEMORY: FAIL")
        raise SystemExit(1)

    # --------------------------------------------------------
    # TEST 7 - ALL CAMPAIGNS
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("TEST 7 - CAMPAIGN HISTORY")
    print("=" * 60)

    campaigns = new_memory.get_all_campaigns()

    print()
    print(
        f"Total campaigns stored: {len(campaigns)}"
    )

    for item in campaigns:
        print()
        print(
            f"ID: {item['id']}"
        )
        print(
            f"Product: {item['product']}"
        )
        print(
            f"Audience: {item['target_audience']}"
        )
        print(
            f"Goal: {item['marketing_goal']}"
        )
        print(
            f"Budget: {item['budget']}"
        )

    if len(campaigns) > 0:
        print()
        print("CAMPAIGN HISTORY: PASS")
    else:
        print()
        print("CAMPAIGN HISTORY: FAIL")
        raise SystemExit(1)

    # --------------------------------------------------------
    # TEST 8 - FINAL MEMORY SUMMARY
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("TEST 8 - MEMORY SUMMARY")
    print("=" * 60)

    final_summary = (
        new_memory.get_memory_summary()
    )

    print()
    print(final_summary)

    if (
        final_summary["campaign_count"] >= 1
        and final_summary["context_count"] >= 1
    ):
        print()
        print("MEMORY SUMMARY: PASS")
    else:
        print()
        print("MEMORY SUMMARY: FAIL")
        raise SystemExit(1)

    # --------------------------------------------------------
    # FINAL RESULT
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("MEMORY VERIFICATION")
    print("=" * 60)

    print()
    print("Database initialization: PASS")
    print("Campaign save: PASS")
    print("Campaign retrieval: PASS")
    print("User context save: PASS")
    print("Campaign search: PASS")
    print("Persistent memory: PASS")
    print("Campaign history: PASS")
    print("Memory summary: PASS")

    print()
    print("=" * 60)
    print("MEMORY TEST COMPLETE - ALL TESTS PASSED")
    print("=" * 60)


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()